### PR TITLE
Fix positions parameter to work

### PR DESCRIPTION
**Pull request by leothehuman**
Position parameter is misplaced in the make files and is redundant in the models.

### CODE REVIEW

**Comment by lostapathy** [comment]
The code in HEAD now is wrong, but this change doesn’t capture the original intent either.  That position param should be passed into printer() from the outer module, not just moved as a default like this.

**Comment by dandancheeseandham** [comment]
Yes, this used to work, and I'd like to keep the functionality of passing the position as part of the make function , and work out where I broke it :smile:

**Comment by dandancheeseandham** [comment]
OK, finally spotted it. There is a simple fix which passes position correctly (which used to work)
Move the position to the printer call
```
// vim: set nospell:
use <models_standard.scad>
use <core.scad>

rc300zl()
  printer(position = [80, 90, 30]);
```

I'll be merging this in with a pull request and other improvements and tidying shortly.

**Comment by leothehuman** [comment]
That's exactly what I did in this PR. (:

**Comment by dandancheeseandham** [comment]
Thanks for pointing that out.
I managed to create conflicts, since it's a simple update I've done it manually and positions now work.
Thanks!

**Pull request closed without merging**
